// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: activity_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 活动状态枚举
type ActivityStatus int32

const (
	ActivityStatus_ACTIVITY_STATUS_UNKNOWN ActivityStatus = 0 // 未知状态
	ActivityStatus_ACTIVITY_STATUS_RUNNING ActivityStatus = 1 // 进行中
	ActivityStatus_ACTIVITY_STATUS_ENDED   ActivityStatus = 2 // 已结束
)

// Enum value maps for ActivityStatus.
var (
	ActivityStatus_name = map[int32]string{
		0: "ACTIVITY_STATUS_UNKNOWN",
		1: "ACTIVITY_STATUS_RUNNING",
		2: "ACTIVITY_STATUS_ENDED",
	}
	ActivityStatus_value = map[string]int32{
		"ACTIVITY_STATUS_UNKNOWN": 0,
		"ACTIVITY_STATUS_RUNNING": 1,
		"ACTIVITY_STATUS_ENDED":   2,
	}
)

func (x ActivityStatus) Enum() *ActivityStatus {
	p := new(ActivityStatus)
	*p = x
	return p
}

func (x ActivityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_type_proto_enumTypes[0].Descriptor()
}

func (ActivityStatus) Type() protoreflect.EnumType {
	return &file_activity_type_proto_enumTypes[0]
}

func (x ActivityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityStatus.Descriptor instead.
func (ActivityStatus) EnumDescriptor() ([]byte, []int) {
	return file_activity_type_proto_rawDescGZIP(), []int{0}
}

// 活动状态
type ActivityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      int32                  `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`               // 活动配置ID
	ActivityId    string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`          // 活动实例ID
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                                       // 活动类型
	CurrentStage  string                 `protobuf:"bytes,4,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`    // 当前阶段
	StageEndTime  int64                  `protobuf:"varint,5,opt,name=stage_end_time,json=stageEndTime,proto3" json:"stage_end_time,omitempty"` // 阶段结束时间戳（秒）
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`            // 活动开始时间戳（秒）
	Status        ActivityStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=api.ActivityStatus" json:"status,omitempty"`           // 活动状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityState) Reset() {
	*x = ActivityState{}
	mi := &file_activity_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityState) ProtoMessage() {}

func (x *ActivityState) ProtoReflect() protoreflect.Message {
	mi := &file_activity_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityState.ProtoReflect.Descriptor instead.
func (*ActivityState) Descriptor() ([]byte, []int) {
	return file_activity_type_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityState) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ActivityState) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *ActivityState) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ActivityState) GetCurrentStage() string {
	if x != nil {
		return x.CurrentStage
	}
	return ""
}

func (x *ActivityState) GetStageEndTime() int64 {
	if x != nil {
		return x.StageEndTime
	}
	return 0
}

func (x *ActivityState) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ActivityState) GetStatus() ActivityStatus {
	if x != nil {
		return x.Status
	}
	return ActivityStatus_ACTIVITY_STATUS_UNKNOWN
}

var File_activity_type_proto protoreflect.FileDescriptor

const file_activity_type_proto_rawDesc = "" +
	"\n" +
	"\x13activity_type.proto\x12\x03api\"\xf8\x01\n" +
	"\rActivityState\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\x05R\bconfigId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12#\n" +
	"\rcurrent_stage\x18\x04 \x01(\tR\fcurrentStage\x12$\n" +
	"\x0estage_end_time\x18\x05 \x01(\x03R\fstageEndTime\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12+\n" +
	"\x06status\x18\a \x01(\x0e2\x13.api.ActivityStatusR\x06status*e\n" +
	"\x0eActivityStatus\x12\x1b\n" +
	"\x17ACTIVITY_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17ACTIVITY_STATUS_RUNNING\x10\x01\x12\x19\n" +
	"\x15ACTIVITY_STATUS_ENDED\x10\x02B/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_activity_type_proto_rawDescOnce sync.Once
	file_activity_type_proto_rawDescData []byte
)

func file_activity_type_proto_rawDescGZIP() []byte {
	file_activity_type_proto_rawDescOnce.Do(func() {
		file_activity_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_type_proto_rawDesc), len(file_activity_type_proto_rawDesc)))
	})
	return file_activity_type_proto_rawDescData
}

var file_activity_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_activity_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_activity_type_proto_goTypes = []any{
	(ActivityStatus)(0),   // 0: api.ActivityStatus
	(*ActivityState)(nil), // 1: api.ActivityState
}
var file_activity_type_proto_depIdxs = []int32{
	0, // 0: api.ActivityState.status:type_name -> api.ActivityStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_activity_type_proto_init() }
func file_activity_type_proto_init() {
	if File_activity_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_type_proto_rawDesc), len(file_activity_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_type_proto_goTypes,
		DependencyIndexes: file_activity_type_proto_depIdxs,
		EnumInfos:         file_activity_type_proto_enumTypes,
		MessageInfos:      file_activity_type_proto_msgTypes,
	}.Build()
	File_activity_type_proto = out.File
	file_activity_type_proto_goTypes = nil
	file_activity_type_proto_depIdxs = nil
}
