// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: doll_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩偶实例
type DollItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 实例ID（雪花ID）
	DollId        int32                  `protobuf:"varint,2,opt,name=doll_id,json=dollId,proto3" json:"doll_id,omitempty"`             // 配置ID
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`                         // 当前品质
	IsLocked      bool                   `protobuf:"varint,4,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`       // 是否锁定
	IsRedeemed    bool                   `protobuf:"varint,5,opt,name=is_redeemed,json=isRedeemed,proto3" json:"is_redeemed,omitempty"` // 是否已兑换实物
	IsFavorite    bool                   `protobuf:"varint,6,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"` // 是否收藏
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // 获得时间（Unix时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollItem) Reset() {
	*x = DollItem{}
	mi := &file_doll_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollItem) ProtoMessage() {}

func (x *DollItem) ProtoReflect() protoreflect.Message {
	mi := &file_doll_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollItem.ProtoReflect.Descriptor instead.
func (*DollItem) Descriptor() ([]byte, []int) {
	return file_doll_type_proto_rawDescGZIP(), []int{0}
}

func (x *DollItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DollItem) GetDollId() int32 {
	if x != nil {
		return x.DollId
	}
	return 0
}

func (x *DollItem) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *DollItem) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *DollItem) GetIsRedeemed() bool {
	if x != nil {
		return x.IsRedeemed
	}
	return false
}

func (x *DollItem) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *DollItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_doll_type_proto protoreflect.FileDescriptor

const file_doll_type_proto_rawDesc = "" +
	"\n" +
	"\x0fdoll_type.proto\x12\x03api\"\xcb\x01\n" +
	"\bDollItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\adoll_id\x18\x02 \x01(\x05R\x06dollId\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12\x1b\n" +
	"\tis_locked\x18\x04 \x01(\bR\bisLocked\x12\x1f\n" +
	"\vis_redeemed\x18\x05 \x01(\bR\n" +
	"isRedeemed\x12\x1f\n" +
	"\vis_favorite\x18\x06 \x01(\bR\n" +
	"isFavorite\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAtB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_doll_type_proto_rawDescOnce sync.Once
	file_doll_type_proto_rawDescData []byte
)

func file_doll_type_proto_rawDescGZIP() []byte {
	file_doll_type_proto_rawDescOnce.Do(func() {
		file_doll_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doll_type_proto_rawDesc), len(file_doll_type_proto_rawDesc)))
	})
	return file_doll_type_proto_rawDescData
}

var file_doll_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_doll_type_proto_goTypes = []any{
	(*DollItem)(nil), // 0: api.DollItem
}
var file_doll_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doll_type_proto_init() }
func file_doll_type_proto_init() {
	if File_doll_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doll_type_proto_rawDesc), len(file_doll_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_doll_type_proto_goTypes,
		DependencyIndexes: file_doll_type_proto_depIdxs,
		MessageInfos:      file_doll_type_proto_msgTypes,
	}.Build()
	File_doll_type_proto = out.File
	file_doll_type_proto_goTypes = nil
	file_doll_type_proto_depIdxs = nil
}
