// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: doll.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取玩偶列表请求
type DollListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollListRequest) Reset() {
	*x = DollListRequest{}
	mi := &file_doll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollListRequest) ProtoMessage() {}

func (x *DollListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollListRequest.ProtoReflect.Descriptor instead.
func (*DollListRequest) Descriptor() ([]byte, []int) {
	return file_doll_proto_rawDescGZIP(), []int{0}
}

// 获取玩偶列表响应
type DollListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.ErrorCode" json:"code,omitempty"`
	Dolls         []*DollItem            `protobuf:"bytes,2,rep,name=dolls,proto3" json:"dolls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollListResponse) Reset() {
	*x = DollListResponse{}
	mi := &file_doll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollListResponse) ProtoMessage() {}

func (x *DollListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollListResponse.ProtoReflect.Descriptor instead.
func (*DollListResponse) Descriptor() ([]byte, []int) {
	return file_doll_proto_rawDescGZIP(), []int{1}
}

func (x *DollListResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *DollListResponse) GetDolls() []*DollItem {
	if x != nil {
		return x.Dolls
	}
	return nil
}

// 收藏/取消收藏请求
type DollFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`             // 玩偶实例ID
	Favorite      bool                   `protobuf:"varint,2,opt,name=favorite,proto3" json:"favorite,omitempty"` // true=收藏, false=取消收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollFavoriteRequest) Reset() {
	*x = DollFavoriteRequest{}
	mi := &file_doll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollFavoriteRequest) ProtoMessage() {}

func (x *DollFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollFavoriteRequest.ProtoReflect.Descriptor instead.
func (*DollFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_doll_proto_rawDescGZIP(), []int{2}
}

func (x *DollFavoriteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DollFavoriteRequest) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

// 收藏/取消收藏响应
type DollFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.ErrorCode" json:"code,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                                   // 玩偶实例ID
	IsFavorite    bool                   `protobuf:"varint,3,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"` // 当前收藏状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollFavoriteResponse) Reset() {
	*x = DollFavoriteResponse{}
	mi := &file_doll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollFavoriteResponse) ProtoMessage() {}

func (x *DollFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollFavoriteResponse.ProtoReflect.Descriptor instead.
func (*DollFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_doll_proto_rawDescGZIP(), []int{3}
}

func (x *DollFavoriteResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *DollFavoriteResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DollFavoriteResponse) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

// 锁定/取消锁定请求
type DollLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`     // 玩偶实例ID
	Lock          bool                   `protobuf:"varint,2,opt,name=lock,proto3" json:"lock,omitempty"` // true=锁定, false=取消锁定
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollLockRequest) Reset() {
	*x = DollLockRequest{}
	mi := &file_doll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollLockRequest) ProtoMessage() {}

func (x *DollLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollLockRequest.ProtoReflect.Descriptor instead.
func (*DollLockRequest) Descriptor() ([]byte, []int) {
	return file_doll_proto_rawDescGZIP(), []int{4}
}

func (x *DollLockRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DollLockRequest) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

// 锁定/取消锁定响应
type DollLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.ErrorCode" json:"code,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                             // 玩偶实例ID
	IsLocked      bool                   `protobuf:"varint,3,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"` // 当前锁定状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollLockResponse) Reset() {
	*x = DollLockResponse{}
	mi := &file_doll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollLockResponse) ProtoMessage() {}

func (x *DollLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollLockResponse.ProtoReflect.Descriptor instead.
func (*DollLockResponse) Descriptor() ([]byte, []int) {
	return file_doll_proto_rawDescGZIP(), []int{5}
}

func (x *DollLockResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *DollLockResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DollLockResponse) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

// 兑换实体玩偶请求
type DollRedeemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 玩偶实例ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollRedeemRequest) Reset() {
	*x = DollRedeemRequest{}
	mi := &file_doll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollRedeemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollRedeemRequest) ProtoMessage() {}

func (x *DollRedeemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollRedeemRequest.ProtoReflect.Descriptor instead.
func (*DollRedeemRequest) Descriptor() ([]byte, []int) {
	return file_doll_proto_rawDescGZIP(), []int{6}
}

func (x *DollRedeemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 兑换实体玩偶响应
type DollRedeemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollRedeemResponse) Reset() {
	*x = DollRedeemResponse{}
	mi := &file_doll_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollRedeemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollRedeemResponse) ProtoMessage() {}

func (x *DollRedeemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doll_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollRedeemResponse.ProtoReflect.Descriptor instead.
func (*DollRedeemResponse) Descriptor() ([]byte, []int) {
	return file_doll_proto_rawDescGZIP(), []int{7}
}

func (x *DollRedeemResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_SUCCESS
}

var File_doll_proto protoreflect.FileDescriptor

const file_doll_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"doll.proto\x12\x03api\x1a\x0fdoll_type.proto\x1a\x0eerr_code.proto\"\x11\n" +
	"\x0fDollListRequest\"[\n" +
	"\x10DollListResponse\x12\"\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0e.api.ErrorCodeR\x04code\x12#\n" +
	"\x05dolls\x18\x02 \x03(\v2\r.api.DollItemR\x05dolls\"A\n" +
	"\x13DollFavoriteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bfavorite\x18\x02 \x01(\bR\bfavorite\"k\n" +
	"\x14DollFavoriteResponse\x12\"\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0e.api.ErrorCodeR\x04code\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x1f\n" +
	"\vis_favorite\x18\x03 \x01(\bR\n" +
	"isFavorite\"5\n" +
	"\x0fDollLockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04lock\x18\x02 \x01(\bR\x04lock\"c\n" +
	"\x10DollLockResponse\x12\"\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0e.api.ErrorCodeR\x04code\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x1b\n" +
	"\tis_locked\x18\x03 \x01(\bR\bisLocked\"#\n" +
	"\x11DollRedeemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x12DollRedeemResponse\x12\"\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0e.api.ErrorCodeR\x04codeB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_doll_proto_rawDescOnce sync.Once
	file_doll_proto_rawDescData []byte
)

func file_doll_proto_rawDescGZIP() []byte {
	file_doll_proto_rawDescOnce.Do(func() {
		file_doll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doll_proto_rawDesc), len(file_doll_proto_rawDesc)))
	})
	return file_doll_proto_rawDescData
}

var file_doll_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_doll_proto_goTypes = []any{
	(*DollListRequest)(nil),      // 0: api.DollListRequest
	(*DollListResponse)(nil),     // 1: api.DollListResponse
	(*DollFavoriteRequest)(nil),  // 2: api.DollFavoriteRequest
	(*DollFavoriteResponse)(nil), // 3: api.DollFavoriteResponse
	(*DollLockRequest)(nil),      // 4: api.DollLockRequest
	(*DollLockResponse)(nil),     // 5: api.DollLockResponse
	(*DollRedeemRequest)(nil),    // 6: api.DollRedeemRequest
	(*DollRedeemResponse)(nil),   // 7: api.DollRedeemResponse
	(ErrorCode)(0),               // 8: api.ErrorCode
	(*DollItem)(nil),             // 9: api.DollItem
}
var file_doll_proto_depIdxs = []int32{
	8, // 0: api.DollListResponse.code:type_name -> api.ErrorCode
	9, // 1: api.DollListResponse.dolls:type_name -> api.DollItem
	8, // 2: api.DollFavoriteResponse.code:type_name -> api.ErrorCode
	8, // 3: api.DollLockResponse.code:type_name -> api.ErrorCode
	8, // 4: api.DollRedeemResponse.code:type_name -> api.ErrorCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_doll_proto_init() }
func file_doll_proto_init() {
	if File_doll_proto != nil {
		return
	}
	file_doll_type_proto_init()
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doll_proto_rawDesc), len(file_doll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_doll_proto_goTypes,
		DependencyIndexes: file_doll_proto_depIdxs,
		MessageInfos:      file_doll_proto_msgTypes,
	}.Build()
	File_doll_proto = out.File
	file_doll_proto_goTypes = nil
	file_doll_proto_depIdxs = nil
}
