// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: err_code.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码
type ErrorCode int32

const (
	ErrorCode_ERR_SUCCESS               ErrorCode = 0  // 成功
	ErrorCode_ERR_TOKEN_INVALID         ErrorCode = 1  // Token 无效
	ErrorCode_ERR_TOKEN_EXPIRED         ErrorCode = 2  // Token 已过期
	ErrorCode_ERR_SESSION_NOT_FOUND     ErrorCode = 3  // 会话不存在
	ErrorCode_ERR_ALREADY_AUTHENTICATED ErrorCode = 4  // 已认证，重复请求
	ErrorCode_ERR_INTERNAL              ErrorCode = 99 // 内部错误
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERR_SUCCESS",
		1:  "ERR_TOKEN_INVALID",
		2:  "ERR_TOKEN_EXPIRED",
		3:  "ERR_SESSION_NOT_FOUND",
		4:  "ERR_ALREADY_AUTHENTICATED",
		99: "ERR_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERR_SUCCESS":               0,
		"ERR_TOKEN_INVALID":         1,
		"ERR_TOKEN_EXPIRED":         2,
		"ERR_SESSION_NOT_FOUND":     3,
		"ERR_ALREADY_AUTHENTICATED": 4,
		"ERR_INTERNAL":              99,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_err_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_err_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_err_code_proto_rawDescGZIP(), []int{0}
}

var File_err_code_proto protoreflect.FileDescriptor

const file_err_code_proto_rawDesc = "" +
	"\n" +
	"\x0eerr_code.proto\x12\x03api*\x96\x01\n" +
	"\tErrorCode\x12\x0f\n" +
	"\vERR_SUCCESS\x10\x00\x12\x15\n" +
	"\x11ERR_TOKEN_INVALID\x10\x01\x12\x15\n" +
	"\x11ERR_TOKEN_EXPIRED\x10\x02\x12\x19\n" +
	"\x15ERR_SESSION_NOT_FOUND\x10\x03\x12\x1d\n" +
	"\x19ERR_ALREADY_AUTHENTICATED\x10\x04\x12\x10\n" +
	"\fERR_INTERNAL\x10cB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_err_code_proto_rawDescOnce sync.Once
	file_err_code_proto_rawDescData []byte
)

func file_err_code_proto_rawDescGZIP() []byte {
	file_err_code_proto_rawDescOnce.Do(func() {
		file_err_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_err_code_proto_rawDesc), len(file_err_code_proto_rawDesc)))
	})
	return file_err_code_proto_rawDescData
}

var file_err_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_err_code_proto_goTypes = []any{
	(ErrorCode)(0), // 0: api.ErrorCode
}
var file_err_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_err_code_proto_init() }
func file_err_code_proto_init() {
	if File_err_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_err_code_proto_rawDesc), len(file_err_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_err_code_proto_goTypes,
		DependencyIndexes: file_err_code_proto_depIdxs,
		EnumInfos:         file_err_code_proto_enumTypes,
	}.Build()
	File_err_code_proto = out.File
	file_err_code_proto_goTypes = nil
	file_err_code_proto_depIdxs = nil
}
