// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: gacha_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 盲盒池信息
type GachaPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 池子ID
	DrawCount     int32                  `protobuf:"varint,2,opt,name=draw_count,json=drawCount,proto3" json:"draw_count,omitempty"` // 玩家已抽次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaPool) Reset() {
	*x = GachaPool{}
	mi := &file_gacha_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaPool) ProtoMessage() {}

func (x *GachaPool) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaPool.ProtoReflect.Descriptor instead.
func (*GachaPool) Descriptor() ([]byte, []int) {
	return file_gacha_type_proto_rawDescGZIP(), []int{0}
}

func (x *GachaPool) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GachaPool) GetDrawCount() int32 {
	if x != nil {
		return x.DrawCount
	}
	return 0
}

// 抽奖奖励
type GachaReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemType      int32                  `protobuf:"varint,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // 奖励类型（1=玩偶, 2=道具）
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                             // 道具ID或掉落ID
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                       // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaReward) Reset() {
	*x = GachaReward{}
	mi := &file_gacha_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaReward) ProtoMessage() {}

func (x *GachaReward) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaReward.ProtoReflect.Descriptor instead.
func (*GachaReward) Descriptor() ([]byte, []int) {
	return file_gacha_type_proto_rawDescGZIP(), []int{1}
}

func (x *GachaReward) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *GachaReward) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GachaReward) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_gacha_type_proto protoreflect.FileDescriptor

const file_gacha_type_proto_rawDesc = "" +
	"\n" +
	"\x10gacha_type.proto\x12\x03api\":\n" +
	"\tGachaPool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"draw_count\x18\x02 \x01(\x05R\tdrawCount\"P\n" +
	"\vGachaReward\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\x05R\bitemType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05countB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_gacha_type_proto_rawDescOnce sync.Once
	file_gacha_type_proto_rawDescData []byte
)

func file_gacha_type_proto_rawDescGZIP() []byte {
	file_gacha_type_proto_rawDescOnce.Do(func() {
		file_gacha_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gacha_type_proto_rawDesc), len(file_gacha_type_proto_rawDesc)))
	})
	return file_gacha_type_proto_rawDescData
}

var file_gacha_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gacha_type_proto_goTypes = []any{
	(*GachaPool)(nil),   // 0: api.GachaPool
	(*GachaReward)(nil), // 1: api.GachaReward
}
var file_gacha_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gacha_type_proto_init() }
func file_gacha_type_proto_init() {
	if File_gacha_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gacha_type_proto_rawDesc), len(file_gacha_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gacha_type_proto_goTypes,
		DependencyIndexes: file_gacha_type_proto_depIdxs,
		MessageInfos:      file_gacha_type_proto_msgTypes,
	}.Build()
	File_gacha_type_proto = out.File
	file_gacha_type_proto_goTypes = nil
	file_gacha_type_proto_depIdxs = nil
}
