// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: gacha.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取盲盒列表请求
type GachaListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaListRequest) Reset() {
	*x = GachaListRequest{}
	mi := &file_gacha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaListRequest) ProtoMessage() {}

func (x *GachaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaListRequest.ProtoReflect.Descriptor instead.
func (*GachaListRequest) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{0}
}

// 获取盲盒列表响应
type GachaListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.ErrorCode" json:"code,omitempty"`
	Pools         []*GachaPool           `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaListResponse) Reset() {
	*x = GachaListResponse{}
	mi := &file_gacha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaListResponse) ProtoMessage() {}

func (x *GachaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaListResponse.ProtoReflect.Descriptor instead.
func (*GachaListResponse) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{1}
}

func (x *GachaListResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *GachaListResponse) GetPools() []*GachaPool {
	if x != nil {
		return x.Pools
	}
	return nil
}

// 抽奖请求
type GachaDrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        int32                  `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"` // 池子ID
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 抽奖次数（1=单抽, 10=十连）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaDrawRequest) Reset() {
	*x = GachaDrawRequest{}
	mi := &file_gacha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaDrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaDrawRequest) ProtoMessage() {}

func (x *GachaDrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaDrawRequest.ProtoReflect.Descriptor instead.
func (*GachaDrawRequest) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{2}
}

func (x *GachaDrawRequest) GetPoolId() int32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *GachaDrawRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 抽奖响应
type GachaDrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.ErrorCode" json:"code,omitempty"`
	Rewards       []*GachaReward         `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty"`                       // 抽奖奖励列表
	DrawCount     int32                  `protobuf:"varint,3,opt,name=draw_count,json=drawCount,proto3" json:"draw_count,omitempty"` // 抽奖后累计次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaDrawResponse) Reset() {
	*x = GachaDrawResponse{}
	mi := &file_gacha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaDrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaDrawResponse) ProtoMessage() {}

func (x *GachaDrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaDrawResponse.ProtoReflect.Descriptor instead.
func (*GachaDrawResponse) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{3}
}

func (x *GachaDrawResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *GachaDrawResponse) GetRewards() []*GachaReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *GachaDrawResponse) GetDrawCount() int32 {
	if x != nil {
		return x.DrawCount
	}
	return 0
}

var File_gacha_proto protoreflect.FileDescriptor

const file_gacha_proto_rawDesc = "" +
	"\n" +
	"\vgacha.proto\x12\x03api\x1a\x10gacha_type.proto\x1a\x0eerr_code.proto\"\x12\n" +
	"\x10GachaListRequest\"]\n" +
	"\x11GachaListResponse\x12\"\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0e.api.ErrorCodeR\x04code\x12$\n" +
	"\x05pools\x18\x02 \x03(\v2\x0e.api.GachaPoolR\x05pools\"A\n" +
	"\x10GachaDrawRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\x05R\x06poolId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x82\x01\n" +
	"\x11GachaDrawResponse\x12\"\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0e.api.ErrorCodeR\x04code\x12*\n" +
	"\arewards\x18\x02 \x03(\v2\x10.api.GachaRewardR\arewards\x12\x1d\n" +
	"\n" +
	"draw_count\x18\x03 \x01(\x05R\tdrawCountB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_gacha_proto_rawDescOnce sync.Once
	file_gacha_proto_rawDescData []byte
)

func file_gacha_proto_rawDescGZIP() []byte {
	file_gacha_proto_rawDescOnce.Do(func() {
		file_gacha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gacha_proto_rawDesc), len(file_gacha_proto_rawDesc)))
	})
	return file_gacha_proto_rawDescData
}

var file_gacha_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gacha_proto_goTypes = []any{
	(*GachaListRequest)(nil),  // 0: api.GachaListRequest
	(*GachaListResponse)(nil), // 1: api.GachaListResponse
	(*GachaDrawRequest)(nil),  // 2: api.GachaDrawRequest
	(*GachaDrawResponse)(nil), // 3: api.GachaDrawResponse
	(ErrorCode)(0),            // 4: api.ErrorCode
	(*GachaPool)(nil),         // 5: api.GachaPool
	(*GachaReward)(nil),       // 6: api.GachaReward
}
var file_gacha_proto_depIdxs = []int32{
	4, // 0: api.GachaListResponse.code:type_name -> api.ErrorCode
	5, // 1: api.GachaListResponse.pools:type_name -> api.GachaPool
	4, // 2: api.GachaDrawResponse.code:type_name -> api.ErrorCode
	6, // 3: api.GachaDrawResponse.rewards:type_name -> api.GachaReward
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gacha_proto_init() }
func file_gacha_proto_init() {
	if File_gacha_proto != nil {
		return
	}
	file_gacha_type_proto_init()
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gacha_proto_rawDesc), len(file_gacha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gacha_proto_goTypes,
		DependencyIndexes: file_gacha_proto_depIdxs,
		MessageInfos:      file_gacha_proto_msgTypes,
	}.Build()
	File_gacha_proto = out.File
	file_gacha_proto_goTypes = nil
	file_gacha_proto_depIdxs = nil
}
