// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: op_code.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpCode 全局协议号定义
type OpCode int32

const (
	OpCode_OP_NONE OpCode = 0
	// 系统协议 (1 - 99)
	OpCode_OP_SYS_HEARTBEAT OpCode = 1 // 心跳
	// 登录系统 (1000 - 1999)
	OpCode_OP_LOGIN_REQ       OpCode = 1000 // 登录请求
	OpCode_OP_LOGIN_RES       OpCode = 1001 // 登录响应
	OpCode_OP_AUTH_REQ        OpCode = 1002 // 网关首次认证请求 (LoginToken)
	OpCode_OP_AUTH_RES        OpCode = 1003 // 网关认证响应 (SessionToken, UID, Roles)
	OpCode_OP_RECONNECT_REQ   OpCode = 1004 // 网关重连请求 (SessionToken)
	OpCode_OP_RECONNECT_RES   OpCode = 1005 // 网关重连响应
	OpCode_OP_SELECT_ROLE_REQ OpCode = 1006 // 选择角色请求
	OpCode_OP_SELECT_ROLE_RES OpCode = 1007 // 选择角色响应
	OpCode_OP_CREATE_ROLE_REQ OpCode = 1008 // 创建角色请求
	OpCode_OP_CREATE_ROLE_RES OpCode = 1009 // 创建角色响应
	OpCode_OP_GET_ROLES_REQ   OpCode = 1010 // 获取角色列表请求
	OpCode_OP_GET_ROLES_RES   OpCode = 1011 // 获取角色列表响应
	// 场景系统 (2000 - 2999)
	OpCode_OP_ENTER_SCENE_REQ OpCode = 2000 // 进入场景请求
	OpCode_OP_ENTER_SCENE_RES OpCode = 2001 // 进入场景响应
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0:    "OP_NONE",
		1:    "OP_SYS_HEARTBEAT",
		1000: "OP_LOGIN_REQ",
		1001: "OP_LOGIN_RES",
		1002: "OP_AUTH_REQ",
		1003: "OP_AUTH_RES",
		1004: "OP_RECONNECT_REQ",
		1005: "OP_RECONNECT_RES",
		1006: "OP_SELECT_ROLE_REQ",
		1007: "OP_SELECT_ROLE_RES",
		1008: "OP_CREATE_ROLE_REQ",
		1009: "OP_CREATE_ROLE_RES",
		1010: "OP_GET_ROLES_REQ",
		1011: "OP_GET_ROLES_RES",
		2000: "OP_ENTER_SCENE_REQ",
		2001: "OP_ENTER_SCENE_RES",
	}
	OpCode_value = map[string]int32{
		"OP_NONE":            0,
		"OP_SYS_HEARTBEAT":   1,
		"OP_LOGIN_REQ":       1000,
		"OP_LOGIN_RES":       1001,
		"OP_AUTH_REQ":        1002,
		"OP_AUTH_RES":        1003,
		"OP_RECONNECT_REQ":   1004,
		"OP_RECONNECT_RES":   1005,
		"OP_SELECT_ROLE_REQ": 1006,
		"OP_SELECT_ROLE_RES": 1007,
		"OP_CREATE_ROLE_REQ": 1008,
		"OP_CREATE_ROLE_RES": 1009,
		"OP_GET_ROLES_REQ":   1010,
		"OP_GET_ROLES_RES":   1011,
		"OP_ENTER_SCENE_REQ": 2000,
		"OP_ENTER_SCENE_RES": 2001,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_op_code_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_op_code_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_op_code_proto_rawDescGZIP(), []int{0}
}

var File_op_code_proto protoreflect.FileDescriptor

const file_op_code_proto_rawDesc = "" +
	"\n" +
	"\rop_code.proto\x12\x03api*\xe7\x02\n" +
	"\x06OpCode\x12\v\n" +
	"\aOP_NONE\x10\x00\x12\x14\n" +
	"\x10OP_SYS_HEARTBEAT\x10\x01\x12\x11\n" +
	"\fOP_LOGIN_REQ\x10\xe8\a\x12\x11\n" +
	"\fOP_LOGIN_RES\x10\xe9\a\x12\x10\n" +
	"\vOP_AUTH_REQ\x10\xea\a\x12\x10\n" +
	"\vOP_AUTH_RES\x10\xeb\a\x12\x15\n" +
	"\x10OP_RECONNECT_REQ\x10\xec\a\x12\x15\n" +
	"\x10OP_RECONNECT_RES\x10\xed\a\x12\x17\n" +
	"\x12OP_SELECT_ROLE_REQ\x10\xee\a\x12\x17\n" +
	"\x12OP_SELECT_ROLE_RES\x10\xef\a\x12\x17\n" +
	"\x12OP_CREATE_ROLE_REQ\x10\xf0\a\x12\x17\n" +
	"\x12OP_CREATE_ROLE_RES\x10\xf1\a\x12\x15\n" +
	"\x10OP_GET_ROLES_REQ\x10\xf2\a\x12\x15\n" +
	"\x10OP_GET_ROLES_RES\x10\xf3\a\x12\x17\n" +
	"\x12OP_ENTER_SCENE_REQ\x10\xd0\x0f\x12\x17\n" +
	"\x12OP_ENTER_SCENE_RES\x10\xd1\x0fB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_op_code_proto_rawDescOnce sync.Once
	file_op_code_proto_rawDescData []byte
)

func file_op_code_proto_rawDescGZIP() []byte {
	file_op_code_proto_rawDescOnce.Do(func() {
		file_op_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_op_code_proto_rawDesc), len(file_op_code_proto_rawDesc)))
	})
	return file_op_code_proto_rawDescData
}

var file_op_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_op_code_proto_goTypes = []any{
	(OpCode)(0), // 0: api.OpCode
}
var file_op_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_op_code_proto_init() }
func file_op_code_proto_init() {
	if File_op_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_op_code_proto_rawDesc), len(file_op_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_code_proto_goTypes,
		DependencyIndexes: file_op_code_proto_depIdxs,
		EnumInfos:         file_op_code_proto_enumTypes,
	}.Build()
	File_op_code_proto = out.File
	file_op_code_proto_goTypes = nil
	file_op_code_proto_depIdxs = nil
}
