// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: op_code.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpCode 全局协议号定义
type OpCode int32

const (
	OpCode_OP_NONE OpCode = 0
	// 系统协议
	OpCode_OP_SYS_HEARTBEAT OpCode = 1 // 心跳
	// 登录系统 (1000 - 1999)
	OpCode_OP_LOGIN_REQ OpCode = 1000 // 登录请求
	OpCode_OP_LOGIN_RES OpCode = 1001 // 登录响应
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0:    "OP_NONE",
		1:    "OP_SYS_HEARTBEAT",
		1000: "OP_LOGIN_REQ",
		1001: "OP_LOGIN_RES",
	}
	OpCode_value = map[string]int32{
		"OP_NONE":          0,
		"OP_SYS_HEARTBEAT": 1,
		"OP_LOGIN_REQ":     1000,
		"OP_LOGIN_RES":     1001,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_op_code_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_op_code_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_op_code_proto_rawDescGZIP(), []int{0}
}

var File_op_code_proto protoreflect.FileDescriptor

const file_op_code_proto_rawDesc = "" +
	"\n" +
	"\rop_code.proto\x12\x03api*Q\n" +
	"\x06OpCode\x12\v\n" +
	"\aOP_NONE\x10\x00\x12\x14\n" +
	"\x10OP_SYS_HEARTBEAT\x10\x01\x12\x11\n" +
	"\fOP_LOGIN_REQ\x10\xe8\a\x12\x11\n" +
	"\fOP_LOGIN_RES\x10\xe9\aB3Z1github.com/lk2023060901/xdooria-proto-api/api;apib\x06proto3"

var (
	file_op_code_proto_rawDescOnce sync.Once
	file_op_code_proto_rawDescData []byte
)

func file_op_code_proto_rawDescGZIP() []byte {
	file_op_code_proto_rawDescOnce.Do(func() {
		file_op_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_op_code_proto_rawDesc), len(file_op_code_proto_rawDesc)))
	})
	return file_op_code_proto_rawDescData
}

var file_op_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_op_code_proto_goTypes = []any{
	(OpCode)(0), // 0: api.OpCode
}
var file_op_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_op_code_proto_init() }
func file_op_code_proto_init() {
	if File_op_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_op_code_proto_rawDesc), len(file_op_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_code_proto_goTypes,
		DependencyIndexes: file_op_code_proto_depIdxs,
		EnumInfos:         file_op_code_proto_enumTypes,
	}.Build()
	File_op_code_proto = out.File
	file_op_code_proto_goTypes = nil
	file_op_code_proto_depIdxs = nil
}
