// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: reward_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 道具奖励（用于发放和返回）
type ItemReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoredItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 奖励的道具列表
	Dolls         []*StoredDoll          `protobuf:"bytes,2,rep,name=dolls,proto3" json:"dolls,omitempty"` // 奖励的玩偶列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReward) Reset() {
	*x = ItemReward{}
	mi := &file_reward_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReward) ProtoMessage() {}

func (x *ItemReward) ProtoReflect() protoreflect.Message {
	mi := &file_reward_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReward.ProtoReflect.Descriptor instead.
func (*ItemReward) Descriptor() ([]byte, []int) {
	return file_reward_type_proto_rawDescGZIP(), []int{0}
}

func (x *ItemReward) GetItems() []*StoredItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemReward) GetDolls() []*StoredDoll {
	if x != nil {
		return x.Dolls
	}
	return nil
}

var File_reward_type_proto protoreflect.FileDescriptor

const file_reward_type_proto_rawDesc = "" +
	"\n" +
	"\x11reward_type.proto\x12\x03api\x1a\x0fitem_type.proto\x1a\x12storage_type.proto\"Z\n" +
	"\n" +
	"ItemReward\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.api.StoredItemR\x05items\x12%\n" +
	"\x05dolls\x18\x02 \x03(\v2\x0f.api.StoredDollR\x05dollsB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_reward_type_proto_rawDescOnce sync.Once
	file_reward_type_proto_rawDescData []byte
)

func file_reward_type_proto_rawDescGZIP() []byte {
	file_reward_type_proto_rawDescOnce.Do(func() {
		file_reward_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reward_type_proto_rawDesc), len(file_reward_type_proto_rawDesc)))
	})
	return file_reward_type_proto_rawDescData
}

var file_reward_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reward_type_proto_goTypes = []any{
	(*ItemReward)(nil), // 0: api.ItemReward
	(*StoredItem)(nil), // 1: api.StoredItem
	(*StoredDoll)(nil), // 2: api.StoredDoll
}
var file_reward_type_proto_depIdxs = []int32{
	1, // 0: api.ItemReward.items:type_name -> api.StoredItem
	2, // 1: api.ItemReward.dolls:type_name -> api.StoredDoll
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reward_type_proto_init() }
func file_reward_type_proto_init() {
	if File_reward_type_proto != nil {
		return
	}
	file_item_type_proto_init()
	file_storage_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reward_type_proto_rawDesc), len(file_reward_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reward_type_proto_goTypes,
		DependencyIndexes: file_reward_type_proto_depIdxs,
		MessageInfos:      file_reward_type_proto_msgTypes,
	}.Build()
	File_reward_type_proto = out.File
	file_reward_type_proto_goTypes = nil
	file_reward_type_proto_depIdxs = nil
}
