// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: role_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoleInfo 角色基础信息
type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`         // 角色ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像URL
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                         // 等级
	VipExp        int32                  `protobuf:"varint,5,opt,name=vip_exp,json=vipExp,proto3" json:"vip_exp,omitempty"`         // VIP经验值
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                       // 角色状态 (0=正常, 1=封禁)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_role_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_role_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_role_type_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoleInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *RoleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleInfo) GetVipExp() int32 {
	if x != nil {
		return x.VipExp
	}
	return 0
}

func (x *RoleInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_role_type_proto protoreflect.FileDescriptor

const file_role_type_proto_rawDesc = "" +
	"\n" +
	"\x0frole_type.proto\x12\x03api\"\xa5\x01\n" +
	"\bRoleInfo\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x17\n" +
	"\avip_exp\x18\x05 \x01(\x05R\x06vipExp\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06statusB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_role_type_proto_rawDescOnce sync.Once
	file_role_type_proto_rawDescData []byte
)

func file_role_type_proto_rawDescGZIP() []byte {
	file_role_type_proto_rawDescOnce.Do(func() {
		file_role_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_type_proto_rawDesc), len(file_role_type_proto_rawDesc)))
	})
	return file_role_type_proto_rawDescData
}

var file_role_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_role_type_proto_goTypes = []any{
	(*RoleInfo)(nil), // 0: api.RoleInfo
}
var file_role_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_type_proto_init() }
func file_role_type_proto_init() {
	if File_role_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_type_proto_rawDesc), len(file_role_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_type_proto_goTypes,
		DependencyIndexes: file_role_type_proto_depIdxs,
		MessageInfos:      file_role_type_proto_msgTypes,
	}.Build()
	File_role_type_proto = out.File
	file_role_type_proto_goTypes = nil
	file_role_type_proto_depIdxs = nil
}
