// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: scene_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 场景信息
type SceneInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         int32                  `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // 地图ID
	Pos           *Position              `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`                   // 位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneInfo) Reset() {
	*x = SceneInfo{}
	mi := &file_scene_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneInfo) ProtoMessage() {}

func (x *SceneInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scene_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneInfo.ProtoReflect.Descriptor instead.
func (*SceneInfo) Descriptor() ([]byte, []int) {
	return file_scene_type_proto_rawDescGZIP(), []int{0}
}

func (x *SceneInfo) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *SceneInfo) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 位置信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Rotation      float32                `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"` // 朝向
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_scene_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_scene_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_scene_type_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Position) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

var File_scene_type_proto protoreflect.FileDescriptor

const file_scene_type_proto_rawDesc = "" +
	"\n" +
	"\x10scene_type.proto\x12\x03api\"C\n" +
	"\tSceneInfo\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\x05R\x05mapId\x12\x1f\n" +
	"\x03pos\x18\x02 \x01(\v2\r.api.PositionR\x03pos\"P\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x02R\brotationB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_scene_type_proto_rawDescOnce sync.Once
	file_scene_type_proto_rawDescData []byte
)

func file_scene_type_proto_rawDescGZIP() []byte {
	file_scene_type_proto_rawDescOnce.Do(func() {
		file_scene_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scene_type_proto_rawDesc), len(file_scene_type_proto_rawDesc)))
	})
	return file_scene_type_proto_rawDescData
}

var file_scene_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scene_type_proto_goTypes = []any{
	(*SceneInfo)(nil), // 0: api.SceneInfo
	(*Position)(nil),  // 1: api.Position
}
var file_scene_type_proto_depIdxs = []int32{
	1, // 0: api.SceneInfo.pos:type_name -> api.Position
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scene_type_proto_init() }
func file_scene_type_proto_init() {
	if File_scene_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scene_type_proto_rawDesc), len(file_scene_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scene_type_proto_goTypes,
		DependencyIndexes: file_scene_type_proto_depIdxs,
		MessageInfos:      file_scene_type_proto_msgTypes,
	}.Build()
	File_scene_type_proto = out.File
	file_scene_type_proto_goTypes = nil
	file_scene_type_proto_depIdxs = nil
}
