// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: scene.proto

package api

import (
	xdooria_proto_common "github.com/lk2023060901/xdooria-proto-common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 进入场景请求
type EnterSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneRequest) Reset() {
	*x = EnterSceneRequest{}
	mi := &file_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneRequest) ProtoMessage() {}

func (x *EnterSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneRequest.ProtoReflect.Descriptor instead.
func (*EnterSceneRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{0}
}

// 进入场景响应
type EnterSceneResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          xdooria_proto_common.ErrCode `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrCode" json:"code,omitempty"` // 错误码
	Role          *RoleInfo                    `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                      // 角色基础信息
	Scene         *SceneInfo                   `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`                    // 场景信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneResponse) Reset() {
	*x = EnterSceneResponse{}
	mi := &file_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneResponse) ProtoMessage() {}

func (x *EnterSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneResponse.ProtoReflect.Descriptor instead.
func (*EnterSceneResponse) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{1}
}

func (x *EnterSceneResponse) GetCode() xdooria_proto_common.ErrCode {
	if x != nil {
		return x.Code
	}
	return xdooria_proto_common.ErrCode(0)
}

func (x *EnterSceneResponse) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *EnterSceneResponse) GetScene() *SceneInfo {
	if x != nil {
		return x.Scene
	}
	return nil
}

var File_scene_proto protoreflect.FileDescriptor

const file_scene_proto_rawDesc = "" +
	"\n" +
	"\vscene.proto\x12\x03api\x1a\verror.proto\x1a\x0frole_type.proto\x1a\x10scene_type.proto\"\x13\n" +
	"\x11EnterSceneRequest\"\x82\x01\n" +
	"\x12EnterSceneResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.common.ErrCodeR\x04code\x12!\n" +
	"\x04role\x18\x02 \x01(\v2\r.api.RoleInfoR\x04role\x12$\n" +
	"\x05scene\x18\x03 \x01(\v2\x0e.api.SceneInfoR\x05sceneB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_scene_proto_rawDescOnce sync.Once
	file_scene_proto_rawDescData []byte
)

func file_scene_proto_rawDescGZIP() []byte {
	file_scene_proto_rawDescOnce.Do(func() {
		file_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scene_proto_rawDesc), len(file_scene_proto_rawDesc)))
	})
	return file_scene_proto_rawDescData
}

var file_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scene_proto_goTypes = []any{
	(*EnterSceneRequest)(nil),         // 0: api.EnterSceneRequest
	(*EnterSceneResponse)(nil),        // 1: api.EnterSceneResponse
	(xdooria_proto_common.ErrCode)(0), // 2: common.ErrCode
	(*RoleInfo)(nil),                  // 3: api.RoleInfo
	(*SceneInfo)(nil),                 // 4: api.SceneInfo
}
var file_scene_proto_depIdxs = []int32{
	2, // 0: api.EnterSceneResponse.code:type_name -> common.ErrCode
	3, // 1: api.EnterSceneResponse.role:type_name -> api.RoleInfo
	4, // 2: api.EnterSceneResponse.scene:type_name -> api.SceneInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_scene_proto_init() }
func file_scene_proto_init() {
	if File_scene_proto != nil {
		return
	}
	file_role_type_proto_init()
	file_scene_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scene_proto_rawDesc), len(file_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scene_proto_goTypes,
		DependencyIndexes: file_scene_proto_depIdxs,
		MessageInfos:      file_scene_proto_msgTypes,
	}.Build()
	File_scene_proto = out.File
	file_scene_proto_goTypes = nil
	file_scene_proto_depIdxs = nil
}
