// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: smelt.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 执行熔炼请求
type SmeltDoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DollIds       []int64                `protobuf:"varint,1,rep,packed,name=doll_ids,json=dollIds,proto3" json:"doll_ids,omitempty"` // 待熔炼的玩偶实例ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmeltDoRequest) Reset() {
	*x = SmeltDoRequest{}
	mi := &file_smelt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmeltDoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmeltDoRequest) ProtoMessage() {}

func (x *SmeltDoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smelt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmeltDoRequest.ProtoReflect.Descriptor instead.
func (*SmeltDoRequest) Descriptor() ([]byte, []int) {
	return file_smelt_proto_rawDescGZIP(), []int{0}
}

func (x *SmeltDoRequest) GetDollIds() []int64 {
	if x != nil {
		return x.DollIds
	}
	return nil
}

// 执行熔炼响应
type SmeltDoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.ErrorCode" json:"code,omitempty"`
	Result        *SmeltResult           `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // 熔炼结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmeltDoResponse) Reset() {
	*x = SmeltDoResponse{}
	mi := &file_smelt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmeltDoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmeltDoResponse) ProtoMessage() {}

func (x *SmeltDoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smelt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmeltDoResponse.ProtoReflect.Descriptor instead.
func (*SmeltDoResponse) Descriptor() ([]byte, []int) {
	return file_smelt_proto_rawDescGZIP(), []int{1}
}

func (x *SmeltDoResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *SmeltDoResponse) GetResult() *SmeltResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_smelt_proto protoreflect.FileDescriptor

const file_smelt_proto_rawDesc = "" +
	"\n" +
	"\vsmelt.proto\x12\x03api\x1a\x10smelt_type.proto\x1a\x0eerr_code.proto\"+\n" +
	"\x0eSmeltDoRequest\x12\x19\n" +
	"\bdoll_ids\x18\x01 \x03(\x03R\adollIds\"_\n" +
	"\x0fSmeltDoResponse\x12\"\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0e.api.ErrorCodeR\x04code\x12(\n" +
	"\x06result\x18\x02 \x01(\v2\x10.api.SmeltResultR\x06resultB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_smelt_proto_rawDescOnce sync.Once
	file_smelt_proto_rawDescData []byte
)

func file_smelt_proto_rawDescGZIP() []byte {
	file_smelt_proto_rawDescOnce.Do(func() {
		file_smelt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smelt_proto_rawDesc), len(file_smelt_proto_rawDesc)))
	})
	return file_smelt_proto_rawDescData
}

var file_smelt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_smelt_proto_goTypes = []any{
	(*SmeltDoRequest)(nil),  // 0: api.SmeltDoRequest
	(*SmeltDoResponse)(nil), // 1: api.SmeltDoResponse
	(ErrorCode)(0),          // 2: api.ErrorCode
	(*SmeltResult)(nil),     // 3: api.SmeltResult
}
var file_smelt_proto_depIdxs = []int32{
	2, // 0: api.SmeltDoResponse.code:type_name -> api.ErrorCode
	3, // 1: api.SmeltDoResponse.result:type_name -> api.SmeltResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_smelt_proto_init() }
func file_smelt_proto_init() {
	if File_smelt_proto != nil {
		return
	}
	file_smelt_type_proto_init()
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smelt_proto_rawDesc), len(file_smelt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smelt_proto_goTypes,
		DependencyIndexes: file_smelt_proto_depIdxs,
		MessageInfos:      file_smelt_proto_msgTypes,
	}.Build()
	File_smelt_proto = out.File
	file_smelt_proto_goTypes = nil
	file_smelt_proto_depIdxs = nil
}
