// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: smelt_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 熔炼结果
type SmeltResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doll          *DollItem              `protobuf:"bytes,1,opt,name=doll,proto3" json:"doll,omitempty"`          // 熔炼产出的新玩偶
	Upgraded      bool                   `protobuf:"varint,2,opt,name=upgraded,proto3" json:"upgraded,omitempty"` // 是否升品成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmeltResult) Reset() {
	*x = SmeltResult{}
	mi := &file_smelt_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmeltResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmeltResult) ProtoMessage() {}

func (x *SmeltResult) ProtoReflect() protoreflect.Message {
	mi := &file_smelt_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmeltResult.ProtoReflect.Descriptor instead.
func (*SmeltResult) Descriptor() ([]byte, []int) {
	return file_smelt_type_proto_rawDescGZIP(), []int{0}
}

func (x *SmeltResult) GetDoll() *DollItem {
	if x != nil {
		return x.Doll
	}
	return nil
}

func (x *SmeltResult) GetUpgraded() bool {
	if x != nil {
		return x.Upgraded
	}
	return false
}

var File_smelt_type_proto protoreflect.FileDescriptor

const file_smelt_type_proto_rawDesc = "" +
	"\n" +
	"\x10smelt_type.proto\x12\x03api\x1a\x0fdoll_type.proto\"L\n" +
	"\vSmeltResult\x12!\n" +
	"\x04doll\x18\x01 \x01(\v2\r.api.DollItemR\x04doll\x12\x1a\n" +
	"\bupgraded\x18\x02 \x01(\bR\bupgradedB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_smelt_type_proto_rawDescOnce sync.Once
	file_smelt_type_proto_rawDescData []byte
)

func file_smelt_type_proto_rawDescGZIP() []byte {
	file_smelt_type_proto_rawDescOnce.Do(func() {
		file_smelt_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smelt_type_proto_rawDesc), len(file_smelt_type_proto_rawDesc)))
	})
	return file_smelt_type_proto_rawDescData
}

var file_smelt_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smelt_type_proto_goTypes = []any{
	(*SmeltResult)(nil), // 0: api.SmeltResult
	(*DollItem)(nil),    // 1: api.DollItem
}
var file_smelt_type_proto_depIdxs = []int32{
	1, // 0: api.SmeltResult.doll:type_name -> api.DollItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_smelt_type_proto_init() }
func file_smelt_type_proto_init() {
	if File_smelt_type_proto != nil {
		return
	}
	file_doll_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smelt_type_proto_rawDesc), len(file_smelt_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smelt_type_proto_goTypes,
		DependencyIndexes: file_smelt_type_proto_depIdxs,
		MessageInfos:      file_smelt_type_proto_msgTypes,
	}.Build()
	File_smelt_type_proto = out.File
	file_smelt_type_proto_goTypes = nil
	file_smelt_type_proto_depIdxs = nil
}
