// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: storage_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩偶存储 - 扩展基础信息
type StoredDoll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *ItemBase              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	IsLocked      bool                   `protobuf:"varint,2,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`       // 是否锁定（防止误销毁）
	IsRedeemed    bool                   `protobuf:"varint,3,opt,name=is_redeemed,json=isRedeemed,proto3" json:"is_redeemed,omitempty"` // 是否已兑换实物
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredDoll) Reset() {
	*x = StoredDoll{}
	mi := &file_storage_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredDoll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredDoll) ProtoMessage() {}

func (x *StoredDoll) ProtoReflect() protoreflect.Message {
	mi := &file_storage_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredDoll.ProtoReflect.Descriptor instead.
func (*StoredDoll) Descriptor() ([]byte, []int) {
	return file_storage_type_proto_rawDescGZIP(), []int{0}
}

func (x *StoredDoll) GetBase() *ItemBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *StoredDoll) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *StoredDoll) GetIsRedeemed() bool {
	if x != nil {
		return x.IsRedeemed
	}
	return false
}

// 玩偶背包
type DollBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoredDoll          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollBag) Reset() {
	*x = DollBag{}
	mi := &file_storage_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollBag) ProtoMessage() {}

func (x *DollBag) ProtoReflect() protoreflect.Message {
	mi := &file_storage_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollBag.ProtoReflect.Descriptor instead.
func (*DollBag) Descriptor() ([]byte, []int) {
	return file_storage_type_proto_rawDescGZIP(), []int{1}
}

func (x *DollBag) GetItems() []*StoredDoll {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_storage_type_proto protoreflect.FileDescriptor

const file_storage_type_proto_rawDesc = "" +
	"\n" +
	"\x12storage_type.proto\x12\x03api\x1a\x0fitem_type.proto\"m\n" +
	"\n" +
	"StoredDoll\x12!\n" +
	"\x04base\x18\x01 \x01(\v2\r.api.ItemBaseR\x04base\x12\x1b\n" +
	"\tis_locked\x18\x02 \x01(\bR\bisLocked\x12\x1f\n" +
	"\vis_redeemed\x18\x03 \x01(\bR\n" +
	"isRedeemed\"0\n" +
	"\aDollBag\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.api.StoredDollR\x05itemsB/Z-github.com/lk2023060901/xdooria-proto-api;apib\x06proto3"

var (
	file_storage_type_proto_rawDescOnce sync.Once
	file_storage_type_proto_rawDescData []byte
)

func file_storage_type_proto_rawDescGZIP() []byte {
	file_storage_type_proto_rawDescOnce.Do(func() {
		file_storage_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_type_proto_rawDesc), len(file_storage_type_proto_rawDesc)))
	})
	return file_storage_type_proto_rawDescData
}

var file_storage_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_storage_type_proto_goTypes = []any{
	(*StoredDoll)(nil), // 0: api.StoredDoll
	(*DollBag)(nil),    // 1: api.DollBag
	(*ItemBase)(nil),   // 2: api.ItemBase
}
var file_storage_type_proto_depIdxs = []int32{
	2, // 0: api.StoredDoll.base:type_name -> api.ItemBase
	0, // 1: api.DollBag.items:type_name -> api.StoredDoll
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storage_type_proto_init() }
func file_storage_type_proto_init() {
	if File_storage_type_proto != nil {
		return
	}
	file_item_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_type_proto_rawDesc), len(file_storage_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_type_proto_goTypes,
		DependencyIndexes: file_storage_type_proto_depIdxs,
		MessageInfos:      file_storage_type_proto_msgTypes,
	}.Build()
	File_storage_type_proto = out.File
	file_storage_type_proto_goTypes = nil
	file_storage_type_proto_depIdxs = nil
}
