// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: storage/item_type.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 物品基类 - 所有存储物品的公共字段
type ItemBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 实例唯一ID (UID)
	ConfigId      uint32                 `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`       // 配置ID（关联配置表）
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // 获得时间（时间戳）
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`    // 最近更新时间（时间戳）
	ExpireAt      uint64                 `protobuf:"varint,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`       // 过期时间（时间戳，0表示永久）
	Count         int64                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`                             // 数量（堆叠用，非堆叠为1）
	IsFavorite    bool                   `protobuf:"varint,7,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"` // 是否收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemBase) Reset() {
	*x = ItemBase{}
	mi := &file_storage_item_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBase) ProtoMessage() {}

func (x *ItemBase) ProtoReflect() protoreflect.Message {
	mi := &file_storage_item_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBase.ProtoReflect.Descriptor instead.
func (*ItemBase) Descriptor() ([]byte, []int) {
	return file_storage_item_type_proto_rawDescGZIP(), []int{0}
}

func (x *ItemBase) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemBase) GetConfigId() uint32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ItemBase) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ItemBase) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ItemBase) GetExpireAt() uint64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *ItemBase) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemBase) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

// 普通道具存储
type StoredItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *ItemBase              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredItem) Reset() {
	*x = StoredItem{}
	mi := &file_storage_item_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredItem) ProtoMessage() {}

func (x *StoredItem) ProtoReflect() protoreflect.Message {
	mi := &file_storage_item_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredItem.ProtoReflect.Descriptor instead.
func (*StoredItem) Descriptor() ([]byte, []int) {
	return file_storage_item_type_proto_rawDescGZIP(), []int{1}
}

func (x *StoredItem) GetBase() *ItemBase {
	if x != nil {
		return x.Base
	}
	return nil
}

// 道具背包
type ItemBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoredItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemBag) Reset() {
	*x = ItemBag{}
	mi := &file_storage_item_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBag) ProtoMessage() {}

func (x *ItemBag) ProtoReflect() protoreflect.Message {
	mi := &file_storage_item_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBag.ProtoReflect.Descriptor instead.
func (*ItemBag) Descriptor() ([]byte, []int) {
	return file_storage_item_type_proto_rawDescGZIP(), []int{2}
}

func (x *ItemBag) GetItems() []*StoredItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 道具变化 - 数量变化的道具
type ItemChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 实例ID
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                          // 当前数量（变化后的最新值）
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemChanged) Reset() {
	*x = ItemChanged{}
	mi := &file_storage_item_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemChanged) ProtoMessage() {}

func (x *ItemChanged) ProtoReflect() protoreflect.Message {
	mi := &file_storage_item_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemChanged.ProtoReflect.Descriptor instead.
func (*ItemChanged) Descriptor() ([]byte, []int) {
	return file_storage_item_type_proto_rawDescGZIP(), []int{3}
}

func (x *ItemChanged) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemChanged) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemChanged) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 道具变化 - 删除的道具
type ItemDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 实例ID
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 删除时的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDeleted) Reset() {
	*x = ItemDeleted{}
	mi := &file_storage_item_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDeleted) ProtoMessage() {}

func (x *ItemDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_storage_item_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDeleted.ProtoReflect.Descriptor instead.
func (*ItemDeleted) Descriptor() ([]byte, []int) {
	return file_storage_item_type_proto_rawDescGZIP(), []int{4}
}

func (x *ItemDeleted) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemDeleted) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 道具变化结果集合
type ItemChangeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         []*ItemBase            `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`     // 新增的道具列表
	Changed       []*ItemChanged         `protobuf:"bytes,2,rep,name=changed,proto3" json:"changed,omitempty"` // 数量变化的道具列表
	Deleted       []*ItemDeleted         `protobuf:"bytes,3,rep,name=deleted,proto3" json:"deleted,omitempty"` // 删除的道具列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemChangeResult) Reset() {
	*x = ItemChangeResult{}
	mi := &file_storage_item_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemChangeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemChangeResult) ProtoMessage() {}

func (x *ItemChangeResult) ProtoReflect() protoreflect.Message {
	mi := &file_storage_item_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemChangeResult.ProtoReflect.Descriptor instead.
func (*ItemChangeResult) Descriptor() ([]byte, []int) {
	return file_storage_item_type_proto_rawDescGZIP(), []int{5}
}

func (x *ItemChangeResult) GetAdded() []*ItemBase {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *ItemChangeResult) GetChanged() []*ItemChanged {
	if x != nil {
		return x.Changed
	}
	return nil
}

func (x *ItemChangeResult) GetDeleted() []*ItemDeleted {
	if x != nil {
		return x.Deleted
	}
	return nil
}

var File_storage_item_type_proto protoreflect.FileDescriptor

const file_storage_item_type_proto_rawDesc = "" +
	"\n" +
	"\x17storage/item_type.proto\x12\astorage\"\xc9\x01\n" +
	"\bItemBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\rR\bconfigId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\texpire_at\x18\x05 \x01(\x04R\bexpireAt\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x03R\x05count\x12\x1f\n" +
	"\vis_favorite\x18\a \x01(\bR\n" +
	"isFavorite\"3\n" +
	"\n" +
	"StoredItem\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.storage.ItemBaseR\x04base\"4\n" +
	"\aItemBag\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.storage.StoredItemR\x05items\"R\n" +
	"\vItemChanged\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"3\n" +
	"\vItemDeleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\x9b\x01\n" +
	"\x10ItemChangeResult\x12'\n" +
	"\x05added\x18\x01 \x03(\v2\x11.storage.ItemBaseR\x05added\x12.\n" +
	"\achanged\x18\x02 \x03(\v2\x14.storage.ItemChangedR\achanged\x12.\n" +
	"\adeleted\x18\x03 \x03(\v2\x14.storage.ItemDeletedR\adeletedB;Z9github.com/lk2023060901/xdooria-proto-api/storage;storageb\x06proto3"

var (
	file_storage_item_type_proto_rawDescOnce sync.Once
	file_storage_item_type_proto_rawDescData []byte
)

func file_storage_item_type_proto_rawDescGZIP() []byte {
	file_storage_item_type_proto_rawDescOnce.Do(func() {
		file_storage_item_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_item_type_proto_rawDesc), len(file_storage_item_type_proto_rawDesc)))
	})
	return file_storage_item_type_proto_rawDescData
}

var file_storage_item_type_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_storage_item_type_proto_goTypes = []any{
	(*ItemBase)(nil),         // 0: storage.ItemBase
	(*StoredItem)(nil),       // 1: storage.StoredItem
	(*ItemBag)(nil),          // 2: storage.ItemBag
	(*ItemChanged)(nil),      // 3: storage.ItemChanged
	(*ItemDeleted)(nil),      // 4: storage.ItemDeleted
	(*ItemChangeResult)(nil), // 5: storage.ItemChangeResult
}
var file_storage_item_type_proto_depIdxs = []int32{
	0, // 0: storage.StoredItem.base:type_name -> storage.ItemBase
	1, // 1: storage.ItemBag.items:type_name -> storage.StoredItem
	0, // 2: storage.ItemChangeResult.added:type_name -> storage.ItemBase
	3, // 3: storage.ItemChangeResult.changed:type_name -> storage.ItemChanged
	4, // 4: storage.ItemChangeResult.deleted:type_name -> storage.ItemDeleted
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_storage_item_type_proto_init() }
func file_storage_item_type_proto_init() {
	if File_storage_item_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_item_type_proto_rawDesc), len(file_storage_item_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_item_type_proto_goTypes,
		DependencyIndexes: file_storage_item_type_proto_depIdxs,
		MessageInfos:      file_storage_item_type_proto_msgTypes,
	}.Build()
	File_storage_item_type_proto = out.File
	file_storage_item_type_proto_goTypes = nil
	file_storage_item_type_proto_depIdxs = nil
}
