// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 物品基类 - 所有存储物品的公共字段
type ItemBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 实例唯一ID (UID)
	ConfigId      uint32                 `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`       // 配置ID（关联配置表）
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // 获得时间（时间戳）
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`    // 最近更新时间（时间戳）
	ExpireAt      uint64                 `protobuf:"varint,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`       // 过期时间（时间戳，0表示永久）
	Count         int64                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`                             // 数量（堆叠用，非堆叠为1）
	IsFavorite    bool                   `protobuf:"varint,7,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"` // 是否收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemBase) Reset() {
	*x = ItemBase{}
	mi := &file_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBase) ProtoMessage() {}

func (x *ItemBase) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBase.ProtoReflect.Descriptor instead.
func (*ItemBase) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ItemBase) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemBase) GetConfigId() uint32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ItemBase) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ItemBase) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ItemBase) GetExpireAt() uint64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *ItemBase) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemBase) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

// 普通道具存储
type StoredItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *ItemBase              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredItem) Reset() {
	*x = StoredItem{}
	mi := &file_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredItem) ProtoMessage() {}

func (x *StoredItem) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredItem.ProtoReflect.Descriptor instead.
func (*StoredItem) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StoredItem) GetBase() *ItemBase {
	if x != nil {
		return x.Base
	}
	return nil
}

// 玩偶存储 - 扩展基础信息
type StoredDoll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *ItemBase              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	IsLocked      bool                   `protobuf:"varint,2,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`       // 是否锁定（防止误销毁）
	IsRedeemed    bool                   `protobuf:"varint,3,opt,name=is_redeemed,json=isRedeemed,proto3" json:"is_redeemed,omitempty"` // 是否已兑换实物
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredDoll) Reset() {
	*x = StoredDoll{}
	mi := &file_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredDoll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredDoll) ProtoMessage() {}

func (x *StoredDoll) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredDoll.ProtoReflect.Descriptor instead.
func (*StoredDoll) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StoredDoll) GetBase() *ItemBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *StoredDoll) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *StoredDoll) GetIsRedeemed() bool {
	if x != nil {
		return x.IsRedeemed
	}
	return false
}

// 道具背包
type ItemBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoredItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemBag) Reset() {
	*x = ItemBag{}
	mi := &file_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBag) ProtoMessage() {}

func (x *ItemBag) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBag.ProtoReflect.Descriptor instead.
func (*ItemBag) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ItemBag) GetItems() []*StoredItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 玩偶背包
type DollBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoredDoll          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DollBag) Reset() {
	*x = DollBag{}
	mi := &file_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DollBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DollBag) ProtoMessage() {}

func (x *DollBag) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DollBag.ProtoReflect.Descriptor instead.
func (*DollBag) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DollBag) GetItems() []*StoredDoll {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_storage_storage_proto protoreflect.FileDescriptor

const file_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x15storage/storage.proto\x12\astorage\"\xc9\x01\n" +
	"\bItemBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\rR\bconfigId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\texpire_at\x18\x05 \x01(\x04R\bexpireAt\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x03R\x05count\x12\x1f\n" +
	"\vis_favorite\x18\a \x01(\bR\n" +
	"isFavorite\"3\n" +
	"\n" +
	"StoredItem\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.storage.ItemBaseR\x04base\"q\n" +
	"\n" +
	"StoredDoll\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.storage.ItemBaseR\x04base\x12\x1b\n" +
	"\tis_locked\x18\x02 \x01(\bR\bisLocked\x12\x1f\n" +
	"\vis_redeemed\x18\x03 \x01(\bR\n" +
	"isRedeemed\"4\n" +
	"\aItemBag\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.storage.StoredItemR\x05items\"4\n" +
	"\aDollBag\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.storage.StoredDollR\x05itemsB;Z9github.com/lk2023060901/xdooria-proto-api/storage;storageb\x06proto3"

var (
	file_storage_storage_proto_rawDescOnce sync.Once
	file_storage_storage_proto_rawDescData []byte
)

func file_storage_storage_proto_rawDescGZIP() []byte {
	file_storage_storage_proto_rawDescOnce.Do(func() {
		file_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_storage_proto_rawDesc), len(file_storage_storage_proto_rawDesc)))
	})
	return file_storage_storage_proto_rawDescData
}

var file_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_storage_storage_proto_goTypes = []any{
	(*ItemBase)(nil),   // 0: storage.ItemBase
	(*StoredItem)(nil), // 1: storage.StoredItem
	(*StoredDoll)(nil), // 2: storage.StoredDoll
	(*ItemBag)(nil),    // 3: storage.ItemBag
	(*DollBag)(nil),    // 4: storage.DollBag
}
var file_storage_storage_proto_depIdxs = []int32{
	0, // 0: storage.StoredItem.base:type_name -> storage.ItemBase
	0, // 1: storage.StoredDoll.base:type_name -> storage.ItemBase
	1, // 2: storage.ItemBag.items:type_name -> storage.StoredItem
	2, // 3: storage.DollBag.items:type_name -> storage.StoredDoll
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_storage_storage_proto_init() }
func file_storage_storage_proto_init() {
	if File_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_storage_proto_rawDesc), len(file_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_storage_proto_goTypes,
		DependencyIndexes: file_storage_storage_proto_depIdxs,
		MessageInfos:      file_storage_storage_proto_msgTypes,
	}.Build()
	File_storage_storage_proto = out.File
	file_storage_storage_proto_goTypes = nil
	file_storage_storage_proto_depIdxs = nil
}
