// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: scene/scene.proto

package scene

import (
	xdooria_proto_common "github.com/lk2023060901/xdooria-proto-common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 进入场景请求
type EnterSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneRequest) Reset() {
	*x = EnterSceneRequest{}
	mi := &file_scene_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneRequest) ProtoMessage() {}

func (x *EnterSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneRequest.ProtoReflect.Descriptor instead.
func (*EnterSceneRequest) Descriptor() ([]byte, []int) {
	return file_scene_scene_proto_rawDescGZIP(), []int{0}
}

// 进入场景响应
type EnterSceneResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          xdooria_proto_common.ErrCode `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrCode" json:"code,omitempty"` // 错误码
	Role          *RoleInfo                    `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                      // 角色基础信息
	Scene         *SceneInfo                   `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`                    // 场景信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneResponse) Reset() {
	*x = EnterSceneResponse{}
	mi := &file_scene_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneResponse) ProtoMessage() {}

func (x *EnterSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneResponse.ProtoReflect.Descriptor instead.
func (*EnterSceneResponse) Descriptor() ([]byte, []int) {
	return file_scene_scene_proto_rawDescGZIP(), []int{1}
}

func (x *EnterSceneResponse) GetCode() xdooria_proto_common.ErrCode {
	if x != nil {
		return x.Code
	}
	return xdooria_proto_common.ErrCode(0)
}

func (x *EnterSceneResponse) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *EnterSceneResponse) GetScene() *SceneInfo {
	if x != nil {
		return x.Scene
	}
	return nil
}

// 角色基础信息
type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`         // 角色ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像URL
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                         // 等级
	VipExp        int32                  `protobuf:"varint,5,opt,name=vip_exp,json=vipExp,proto3" json:"vip_exp,omitempty"`         // VIP经验值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_scene_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scene_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_scene_scene_proto_rawDescGZIP(), []int{2}
}

func (x *RoleInfo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoleInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *RoleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleInfo) GetVipExp() int32 {
	if x != nil {
		return x.VipExp
	}
	return 0
}

// 场景信息
type SceneInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         int32                  `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // 地图ID
	Pos           *Position              `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`                   // 位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneInfo) Reset() {
	*x = SceneInfo{}
	mi := &file_scene_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneInfo) ProtoMessage() {}

func (x *SceneInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scene_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneInfo.ProtoReflect.Descriptor instead.
func (*SceneInfo) Descriptor() ([]byte, []int) {
	return file_scene_scene_proto_rawDescGZIP(), []int{3}
}

func (x *SceneInfo) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *SceneInfo) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 位置信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Rotation      float32                `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"` // 朝向
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_scene_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_scene_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_scene_scene_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Position) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

var File_scene_scene_proto protoreflect.FileDescriptor

const file_scene_scene_proto_rawDesc = "" +
	"\n" +
	"\x11scene/scene.proto\x12\x05scene\x1a\verror.proto\"\x13\n" +
	"\x11EnterSceneRequest\"\x86\x01\n" +
	"\x12EnterSceneResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.common.ErrCodeR\x04code\x12#\n" +
	"\x04role\x18\x02 \x01(\v2\x0f.scene.RoleInfoR\x04role\x12&\n" +
	"\x05scene\x18\x03 \x01(\v2\x10.scene.SceneInfoR\x05scene\"\x8d\x01\n" +
	"\bRoleInfo\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x17\n" +
	"\avip_exp\x18\x05 \x01(\x05R\x06vipExp\"E\n" +
	"\tSceneInfo\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\x05R\x05mapId\x12!\n" +
	"\x03pos\x18\x02 \x01(\v2\x0f.scene.PositionR\x03pos\"P\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x02R\brotationB7Z5github.com/lk2023060901/xdooria-proto-api/scene;sceneb\x06proto3"

var (
	file_scene_scene_proto_rawDescOnce sync.Once
	file_scene_scene_proto_rawDescData []byte
)

func file_scene_scene_proto_rawDescGZIP() []byte {
	file_scene_scene_proto_rawDescOnce.Do(func() {
		file_scene_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scene_scene_proto_rawDesc), len(file_scene_scene_proto_rawDesc)))
	})
	return file_scene_scene_proto_rawDescData
}

var file_scene_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scene_scene_proto_goTypes = []any{
	(*EnterSceneRequest)(nil),         // 0: scene.EnterSceneRequest
	(*EnterSceneResponse)(nil),        // 1: scene.EnterSceneResponse
	(*RoleInfo)(nil),                  // 2: scene.RoleInfo
	(*SceneInfo)(nil),                 // 3: scene.SceneInfo
	(*Position)(nil),                  // 4: scene.Position
	(xdooria_proto_common.ErrCode)(0), // 5: common.ErrCode
}
var file_scene_scene_proto_depIdxs = []int32{
	5, // 0: scene.EnterSceneResponse.code:type_name -> common.ErrCode
	2, // 1: scene.EnterSceneResponse.role:type_name -> scene.RoleInfo
	3, // 2: scene.EnterSceneResponse.scene:type_name -> scene.SceneInfo
	4, // 3: scene.SceneInfo.pos:type_name -> scene.Position
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scene_scene_proto_init() }
func file_scene_scene_proto_init() {
	if File_scene_scene_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scene_scene_proto_rawDesc), len(file_scene_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scene_scene_proto_goTypes,
		DependencyIndexes: file_scene_scene_proto_depIdxs,
		MessageInfos:      file_scene_scene_proto_msgTypes,
	}.Build()
	File_scene_scene_proto = out.File
	file_scene_scene_proto_goTypes = nil
	file_scene_scene_proto_depIdxs = nil
}
